services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: tienda
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wp-clase-2026
      MARIADB_ROOT_PASSWORD: root-clase-2026
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.3-apache
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8088:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: tienda
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wp-clase-2026
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') { $$_SERVER['HTTPS'] = 'on'; }
        if (isset($$_SERVER['HTTP_X_FORWARDED_HOST'])) { $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST']; }
        if (isset($$_SERVER['HTTP_HOST'])) {
          $$esquema = (!empty($$_SERVER['HTTPS']) && $$_SERVER['HTTPS'] === 'on') ? 'https' : 'http';
          define('WP_HOME', $$esquema . '://' . $$_SERVER['HTTP_HOST']);
          define('WP_SITEURL', $$esquema . '://' . $$_SERVER['HTTP_HOST']);
        }
        define('WP_MEMORY_LIMIT', '256M');
    volumes:
      - wp_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8089:80"
    environment:
      PMA_HOST: db

  tunel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://wordpress:80
    depends_on:
      - wordpress
    profiles: ["publico"]

volumes:
  db_data:
  wp_data:
